### ISSUE TITLE
Error 3 with Ion Pro RT

### ISSUE THREAD

**Issue by peter7475** [maca88/BikeLightsControl#4]
I've had Error 3 appearing since around November last year, i.e. around the release of v 8.0. Just had a play around and it looks like it is the two flashing modes - day flash and night flash - which are not working, i.e. if I remove options for both of these then it will run OK. I'm on a Garmin Edge 1030. These options were working fine before (so they are supported by the light) - perhaps there was something in the update which clobbered these. 

Happy to help test as necessary.

(Great app by the way - thanks for all your efforts!)

**Comment by maca88** [comment]
Can you post the configuration that is not working (Error 3), so that I can check what is wrong with it?

For Ion Pro RT and Edge 1030, this configuration should work:

`#4587520,196641####7,6:Ion Pro RT!2,:-1,Off:0!1,High:1!1,Medium:2!1,Low:5!1,Day Flash:63!1,Night Flash:62##0::#0:0#B2713#1##0#0`

**Comment by peter7475** [comment]
Thanks for the quick response. This one is not working:
#4587520,196641####7,6:Ion Pro RT!2,:-1,Off:0!1,High:1!1,Medium:2!1,Low:5!1,Night Flash:62!1,Day Flash:63##0::#0:0#B2713#1##0#0
which seems to match yours (except ordering). I just tried yours and I get Error 3 again.

This one does work:
#4587520,196641####5,4:Ion Pro RT!2,:-1,Off:0!1,High:1!1,Medium:2!1,Low:5##0::#0:0#B2713#1##0#0

**Comment by maca88** [comment]
Huh that is really strange, I tried your configuration with my Ion RT Pro + Edge 1000 and it works. It seems like that your Ion Pro RT light has different light modes than mine. Can you please try to clean (empty) the `Lights Configuration` app settings and report back which numbers are displayed on the buttons?

On my Ion Pro I have: 0, 1, 2, 5, 63, 62

**Comment by peter7475** [comment]
Interestingly I have N, off, 1, 2,5,13,14. Buttons 1, 2, 5 work but 13, 14 are highlighted for a second then go back to off. The light does nothing in that case.

**Comment by maca88** [comment]
There must be something wrong either with the Garmin implementation for the light network, which could be broken by an Edge firmware update or with the firmware of the light. Due to the fact that the light worked some time ago and its firmware cannot be upgraded, I suspect that the issues lies in the Garmin firmware. From the API documentation number 13 should be for "Turn signal right" and 14 for "Hazard - right and left signals flash", which doesn't make sense for Ion Pro RT.

In order to detect where the issue lies, you can try to use the Individual Light Network feature, which is an alternative light network implementation used for lights with partial ANT+ support, but it can be also used for other ANT+ lights.
In order to setup the Individual Light Network, you need to first disable the Garmin light network in Sensors menu by removing the paired light or disable it (without this step Individual Light Network won't work) and then go to the [Lights Configurator](https://maca88.github.io/BikeLightsControl/) and do the following:
1. Select Edge 1030
2. Check Use Individual Network
3. Select Ion Pro RT for the headlight
4. Set the `Device number` (click on the question mark on how to get it)
5. Copy the configuration and paste it in the `Lights Configuration` app settings
6. Test whether the Error 3 appears

**Comment by peter7475** [comment]
Ok - just tested that and I still get error 3, unfortunately...

As a reference my wife has the same light so I've tried hers (just in standard Garmin network) and see the same issue - numbers are slightly different though
![image](https://user-images.githubusercontent.com/97365180/148681442-1161b8bc-79e0-440b-a0b2-0d8d573d1c7e.jpeg)

My Garmin says I'm on v13.20.

**Comment by maca88** [comment]
Ok so then it is definitively something wrong with the light. Did you try to reset the light by holding the power button (https://manuals.plus/bontrager/ion-pro-ion-200-rt-flare-rt-gps-bicycle-light-user-manual#reset)?

I really don't understand how it is possible that you have not just one, but two lights with the same problem, this is the first time that someone reported such issue. If the light modes worked a few months ago, then perhaps the reset of the light should do the trick in case you didn't tried it yet. Please let me know if the factory reset worked.

**Comment by peter7475** [comment]
We have a solution! The factory reset fixed the light - I did that and it reverted to the 62/63 codes for flashing modes. Then the configs from before worked.

As you say, strange that this was the same issue on both lights. I don't think we've done anything unusual - I tend to leave my wife's light alone anyway so I don't get into trouble for breaking it!

Thanks for you help with this! And thanks again for the great app.

**Comment by maca88** [comment]
That is good to hear, thanks for letting me know that the reset worked.
