### ISSUE TITLE
Version 0.9 cannot be installed on Garmin 530

### ISSUE THREAD

**Issue by eli71de** [maca88/BikeLightsControl#5]
Garmin 530 is not in the list of compatible devices.

**Comment by maca88** [comment]
Garmin Edge 530 was removed from the compatible devices as it received negative reviews due to the fact that it is a stripped version of [maca88/SmartBikeLights](https://github.com/maca88/SmartBikeLights). As Edge 530 has CIQ 3.2, it is possible to change the light modes manually by using the data field menu (https://github.com/maca88/SmartBikeLights#changing-control-modes).

**Comment by eli71de** [comment]
Ok, thanks for the explanation. I will use the data field instead.
